site_name: Abril Linares Mendoza
site_url: https://abrillm456.github.io/my-website/

theme:
  name: material
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: pink
      accent: pink

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: pink
      accent: pink

plugins:
  - search

nav:
  - Home: index.md
  - About: about.md
